apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: kube-proxy
  labels:
    component: kube-proxy
    tier: control-plane
spec:
  containers:
  - name: kube-proxy
    command:
    - /usr/local/bin/kube-proxy
    - --config=/var/lib/kube-proxy/config.conf
    - --hostname-override=$(NODE_NAME)
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    image: k8s.gcr.io/kube-proxy:v1.15.4
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/kube-proxy/kubeconfig.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /var/lib/kube-proxy/config.conf
      name: kube-proxy
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  priorityClassName: system-node-critical
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/lib/kubernetes/config/kube-proxy.yaml
      type: FileOrCreate
    name: kube-proxy
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /lib/modules
    name: lib-modules
